// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDml9kTFFhM2PhwZfIpXuTHv4sI8yS9mDg',
    appId: '1:514456644765:web:308a86feb6340711103874',
    messagingSenderId: '514456644765',
    projectId: 'login-app-9fe84',
    authDomain: 'login-app-9fe84.firebaseapp.com',
    storageBucket: 'login-app-9fe84.appspot.com',
    measurementId: 'G-89XF1GZGV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxzLcovseJAg3A86VPi9ibmDGXzSx9OY',
    appId: '1:514456644765:android:a4caf51c7116bff6103874',
    messagingSenderId: '514456644765',
    projectId: 'login-app-9fe84',
    storageBucket: 'login-app-9fe84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtofDIhfowo9xa5LFs4-SKmwdUnST6ZUw',
    appId: '1:514456644765:ios:43605dd4460def85103874',
    messagingSenderId: '514456644765',
    projectId: 'login-app-9fe84',
    storageBucket: 'login-app-9fe84.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtofDIhfowo9xa5LFs4-SKmwdUnST6ZUw',
    appId: '1:514456644765:ios:43605dd4460def85103874',
    messagingSenderId: '514456644765',
    projectId: 'login-app-9fe84',
    storageBucket: 'login-app-9fe84.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDml9kTFFhM2PhwZfIpXuTHv4sI8yS9mDg',
    appId: '1:514456644765:web:cdf7f12cffb7d2f8103874',
    messagingSenderId: '514456644765',
    projectId: 'login-app-9fe84',
    authDomain: 'login-app-9fe84.firebaseapp.com',
    storageBucket: 'login-app-9fe84.appspot.com',
    measurementId: 'G-66BSFN4R3H',
  );
}
